// @generated by ipc/codegen.mjs from ipc/schema.json — DO NOT EDIT

use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Hit {
    pub name: String,
    pub path: String,
    pub score: f32,
    pub size_bytes: u32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BuildIndexRequest {
    pub roots: Vec<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BuildIndexResponse {
    pub file_count: u32,
    pub elapsed_ms: u32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchRequest {
    pub query: String,
    pub limit: u32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchResponse {
    pub hits: Vec<Hit>,
    pub elapsed_micros: u32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CoreInfoRequest {}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CoreInfoResponse {
    pub version: String,
    pub indexed_files: u32,
}

/// core 必须实现的命令集合。schema 增删命令时，这里会立刻编译不过。
pub trait CommandHandlers {
    /// 扫描给定根目录，在 Rust 侧建立文件索引
    fn build_index(&mut self, request: BuildIndexRequest) -> Result<BuildIndexResponse, String>;
    /// 在已建索引上做模糊搜索，按得分排序返回
    fn search(&mut self, request: SearchRequest) -> Result<SearchResponse, String>;
    /// 读取 core 版本与当前索引规模
    fn core_info(&mut self, request: CoreInfoRequest) -> Result<CoreInfoResponse, String>;
}

#[derive(Deserialize)]
struct Envelope {
    id: u64,
    command: String,
    #[serde(default)]
    payload: Value,
}

fn ok_response(id: u64, payload: Value) -> String {
    serde_json::json!({ "id": id, "ok": true, "payload": payload }).to_string()
}

fn error_response(id: u64, message: &str) -> String {
    serde_json::json!({ "id": id, "ok": false, "error": message }).to_string()
}

fn decode<T: serde::de::DeserializeOwned>(payload: Value) -> Result<T, String> {
    serde_json::from_value(payload).map_err(|e| format!("payload 解码失败: {e}"))
}

fn encode<T: Serialize>(value: T) -> Result<Value, String> {
    serde_json::to_value(value).map_err(|e| format!("响应编码失败: {e}"))
}

/// 把一条 JSON 信封路由到对应的 handler，并把结果编码回 JSON 信封。
pub fn dispatch<H: CommandHandlers>(handlers: &mut H, envelope_json: &str) -> String {
    let envelope: Envelope = match serde_json::from_str(envelope_json) {
        Ok(value) => value,
        Err(error) => return error_response(0, &format!("信封解析失败: {error}")),
    };

    let result = match envelope.command.as_str() {
        "buildIndex" => decode(envelope.payload)
            .and_then(|request| handlers.build_index(request))
            .and_then(encode),
        "search" => decode(envelope.payload)
            .and_then(|request| handlers.search(request))
            .and_then(encode),
        "coreInfo" => decode(envelope.payload)
            .and_then(|request| handlers.core_info(request))
            .and_then(encode),
        unknown => Err(format!("未知命令: {unknown}")),
    };

    match result {
        Ok(payload) => ok_response(envelope.id, payload),
        Err(message) => error_response(envelope.id, &message),
    }
}
