// @generated by ipc/codegen.mjs from ipc/schema.json — DO NOT EDIT

import Foundation

/// IPC 契约在 Swift 侧的命名空间。
nonisolated enum RustCoreIPC {
    nonisolated struct Hit: Codable, Hashable, Sendable {
        var name: String
        var path: String
        var score: Float
        var sizeBytes: UInt32

        init(name: String, path: String, score: Float, sizeBytes: UInt32) {
            self.name = name
            self.path = path
            self.score = score
            self.sizeBytes = sizeBytes
        }
    }

    nonisolated struct BuildIndexRequest: Codable, Hashable, Sendable {
        var roots: [String]

        init(roots: [String]) {
            self.roots = roots
        }
    }

    nonisolated struct BuildIndexResponse: Codable, Hashable, Sendable {
        var fileCount: UInt32
        var elapsedMs: UInt32

        init(fileCount: UInt32, elapsedMs: UInt32) {
            self.fileCount = fileCount
            self.elapsedMs = elapsedMs
        }
    }

    nonisolated struct SearchRequest: Codable, Hashable, Sendable {
        var query: String
        var limit: UInt32

        init(query: String, limit: UInt32) {
            self.query = query
            self.limit = limit
        }
    }

    nonisolated struct SearchResponse: Codable, Hashable, Sendable {
        var hits: [Hit]
        var elapsedMicros: UInt32

        init(hits: [Hit], elapsedMicros: UInt32) {
            self.hits = hits
            self.elapsedMicros = elapsedMicros
        }
    }

    nonisolated struct CoreInfoRequest: Codable, Hashable, Sendable {
        init() {}
    }

    nonisolated struct CoreInfoResponse: Codable, Hashable, Sendable {
        var version: String
        var indexedFiles: UInt32

        init(version: String, indexedFiles: UInt32) {
            self.version = version
            self.indexedFiles = indexedFiles
        }
    }

    /// schema 里声明的全部命令。
    nonisolated enum Command: String, CaseIterable, Sendable {
        case buildIndex
        case search
        case coreInfo
    }
}

/// 原生壳自己也拿到一份类型化 client —— 它不只是给 WebView 做转发。
extension RustCore {
    /// 扫描给定根目录，在 Rust 侧建立文件索引
    nonisolated func buildIndex(_ request: RustCoreIPC.BuildIndexRequest) throws -> RustCoreIPC.BuildIndexResponse {
        try call(.buildIndex, request)
    }

    /// 在已建索引上做模糊搜索，按得分排序返回
    nonisolated func search(_ request: RustCoreIPC.SearchRequest) throws -> RustCoreIPC.SearchResponse {
        try call(.search, request)
    }

    /// 读取 core 版本与当前索引规模
    nonisolated func coreInfo(_ request: RustCoreIPC.CoreInfoRequest) throws -> RustCoreIPC.CoreInfoResponse {
        try call(.coreInfo, request)
    }

}
