#!/usr/bin/env node
// RustCore IPC 代码生成器。
//
// 读取 ipc/schema.json，为三个运行时各生成一份类型化客户端：
//   web/src/ipc/generated.ts            —— WebView 里的 React UI
//   ios-lab/RustCore/RustCoreIPC.generated.swift —— 原生壳
//   rust/rustcore/src/ipc_generated.rs  —— Rust core
//
// 这是「接口只声明一次，为每一端生成类型化 client」的最小实现：
// 契约改一处，三端同时在编译期报错。

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const BANNER = "// @generated by ipc/codegen.mjs from ipc/schema.json — DO NOT EDIT";

const schema = JSON.parse(readFileSync(join(ROOT, "ipc/schema.json"), "utf8"));

// ---------------------------------------------------------------- 类型系统

/** 把 `"Hit[]"` 解析成 `{ base: "Hit", isArray: true }`。 */
function parseType(spec) {
  const isArray = spec.endsWith("[]");
  return { base: isArray ? spec.slice(0, -2) : spec, isArray };
}

const SCALARS = {
  string: { ts: "string", swift: "String", rust: "String" },
  u32: { ts: "number", swift: "UInt32", rust: "u32" },
  f32: { ts: "number", swift: "Float", rust: "f32" },
  bool: { ts: "boolean", swift: "Bool", rust: "bool" },
};

function renderType(spec, lang) {
  const { base, isArray } = parseType(spec);
  const scalar = SCALARS[base];
  if (!scalar && !schema.types[base]) {
    throw new Error(`schema 引用了未知类型: ${spec}`);
  }
  const inner = scalar ? scalar[lang] : base;
  if (!isArray) return inner;
  return lang === "ts" ? `${inner}[]` : lang === "swift" ? `[${inner}]` : `Vec<${inner}>`;
}

const pascal = (s) => s[0].toUpperCase() + s.slice(1);
const snake = (s) => s.replace(/[A-Z]/g, (c) => `_${c.toLowerCase()}`);

const commands = schema.commands.map((c) => ({
  ...c,
  reqType: `${pascal(c.name)}Request`,
  resType: `${pascal(c.name)}Response`,
}));
const sharedTypes = Object.entries(schema.types ?? {});

/** 每条命令的 request/response 结构体，加上 schema 里的共享类型。 */
function allStructs() {
  const out = sharedTypes.map(([name, fields]) => [name, fields]);
  for (const c of commands) {
    out.push([c.reqType, c.request]);
    out.push([c.resType, c.response]);
  }
  return out;
}

function write(relPath, body) {
  const abs = join(ROOT, relPath);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, body);
  console.log(`  generated ${relPath}`);
}

// ---------------------------------------------------------------- TypeScript

function emitTypeScript() {
  const lines = [BANNER, "", 'import { invoke } from "./transport";', ""];

  for (const [name, fields] of allStructs()) {
    const entries = Object.entries(fields);
    if (entries.length === 0) {
      lines.push(`export interface ${name} {}`, "");
      continue;
    }
    lines.push(`export interface ${name} {`);
    for (const [field, spec] of entries) {
      lines.push(`  ${field}: ${renderType(spec, "ts")};`);
    }
    lines.push("}", "");
  }

  lines.push("/** Rust core 的类型化客户端。每个方法都是一次跨 WebView → 原生壳 → Rust 的往返。 */");
  lines.push("export const ipc = {");
  for (const c of commands) {
    if (c.doc) lines.push(`  /** ${c.doc} */`);
    lines.push(
      `  ${c.name}(request: ${c.reqType}): Promise<${c.resType}> {`,
      `    return invoke<${c.reqType}, ${c.resType}>("${c.name}", request);`,
      `  },`,
    );
  }
  lines.push("};", "");

  write("web/src/ipc/generated.ts", lines.join("\n"));
}

// ---------------------------------------------------------------- Swift

function emitSwift() {
  // 工程开了 SWIFT_DEFAULT_ACTOR_ISOLATION = MainActor，契约类型必须显式声明
  // nonisolated，否则它们的 Codable conformance 也会被绑到主 actor，
  // 后台线程上的编解码在 Swift 6 模式下会直接编译失败。
  const lines = [
    BANNER,
    "",
    "import Foundation",
    "",
    "/// IPC 契约在 Swift 侧的命名空间。",
    "nonisolated enum RustCoreIPC {",
  ];

  for (const [name, fields] of allStructs()) {
    const entries = Object.entries(fields);
    lines.push(`    nonisolated struct ${name}: Codable, Hashable, Sendable {`);
    for (const [field, spec] of entries) {
      lines.push(`        var ${field}: ${renderType(spec, "swift")}`);
    }
    if (entries.length > 0) {
      const params = entries.map(([f, s]) => `${f}: ${renderType(s, "swift")}`).join(", ");
      lines.push("", `        init(${params}) {`);
      for (const [field] of entries) lines.push(`            self.${field} = ${field}`);
      lines.push("        }");
    } else {
      lines.push("        init() {}");
    }
    lines.push("    }", "");
  }

  lines.push("    /// schema 里声明的全部命令。", "    nonisolated enum Command: String, CaseIterable, Sendable {");
  for (const c of commands) lines.push(`        case ${c.name}`);
  lines.push("    }", "}", "");

  lines.push("/// 原生壳自己也拿到一份类型化 client —— 它不只是给 WebView 做转发。");
  lines.push("extension RustCore {");
  for (const c of commands) {
    if (c.doc) lines.push(`    /// ${c.doc}`);
    lines.push(
      `    nonisolated func ${c.name}(_ request: RustCoreIPC.${c.reqType}) throws -> RustCoreIPC.${c.resType} {`,
      `        try call(.${c.name}, request)`,
      `    }`,
      "",
    );
  }
  lines.push("}", "");

  write("ios-lab/RustCore/RustCoreIPC.generated.swift", lines.join("\n"));
}

// ---------------------------------------------------------------- Rust

function emitRust() {
  const lines = [
    BANNER,
    "",
    "use serde::{Deserialize, Serialize};",
    "use serde_json::Value;",
    "",
  ];

  for (const [name, fields] of allStructs()) {
    const entries = Object.entries(fields);
    lines.push("#[derive(Debug, Clone, Default, Serialize, Deserialize)]");
    lines.push('#[serde(rename_all = "camelCase")]');
    if (entries.length === 0) {
      lines.push(`pub struct ${name} {}`, "");
      continue;
    }
    lines.push(`pub struct ${name} {`);
    for (const [field, spec] of entries) {
      lines.push(`    pub ${snake(field)}: ${renderType(spec, "rust")},`);
    }
    lines.push("}", "");
  }

  lines.push(
    "/// core 必须实现的命令集合。schema 增删命令时，这里会立刻编译不过。",
    "pub trait CommandHandlers {",
  );
  for (const c of commands) {
    if (c.doc) lines.push(`    /// ${c.doc}`);
    lines.push(
      `    fn ${snake(c.name)}(&mut self, request: ${c.reqType}) -> Result<${c.resType}, String>;`,
    );
  }
  lines.push("}", "");

  lines.push(
    "#[derive(Deserialize)]",
    "struct Envelope {",
    "    id: u64,",
    "    command: String,",
    "    #[serde(default)]",
    "    payload: Value,",
    "}",
    "",
    "fn ok_response(id: u64, payload: Value) -> String {",
    '    serde_json::json!({ "id": id, "ok": true, "payload": payload }).to_string()',
    "}",
    "",
    "fn error_response(id: u64, message: &str) -> String {",
    '    serde_json::json!({ "id": id, "ok": false, "error": message }).to_string()',
    "}",
    "",
    "fn decode<T: serde::de::DeserializeOwned>(payload: Value) -> Result<T, String> {",
    "    serde_json::from_value(payload).map_err(|e| format!(\"payload 解码失败: {e}\"))",
    "}",
    "",
    "fn encode<T: Serialize>(value: T) -> Result<Value, String> {",
    "    serde_json::to_value(value).map_err(|e| format!(\"响应编码失败: {e}\"))",
    "}",
    "",
    "/// 把一条 JSON 信封路由到对应的 handler，并把结果编码回 JSON 信封。",
    "pub fn dispatch<H: CommandHandlers>(handlers: &mut H, envelope_json: &str) -> String {",
    "    let envelope: Envelope = match serde_json::from_str(envelope_json) {",
    "        Ok(value) => value,",
    "        Err(error) => return error_response(0, &format!(\"信封解析失败: {error}\")),",
    "    };",
    "",
    "    let result = match envelope.command.as_str() {",
  );
  for (const c of commands) {
    lines.push(
      `        "${c.name}" => decode(envelope.payload)`,
      `            .and_then(|request| handlers.${snake(c.name)}(request))`,
      "            .and_then(encode),",
    );
  }
  lines.push(
    '        unknown => Err(format!("未知命令: {unknown}")),',
    "    };",
    "",
    "    match result {",
    "        Ok(payload) => ok_response(envelope.id, payload),",
    "        Err(message) => error_response(envelope.id, &message),",
    "    }",
    "}",
    "",
  );

  write("rust/rustcore/src/ipc_generated.rs", lines.join("\n"));
}

console.log(`ipc codegen: ${commands.length} commands, ${sharedTypes.length} shared types`);
emitTypeScript();
emitSwift();
emitRust();
