// @generated by ipc/codegen.mjs from ipc/schema.json — DO NOT EDIT

import { invoke } from "./transport";

export interface Hit {
  name: string;
  path: string;
  score: number;
  sizeBytes: number;
}

export interface BuildIndexRequest {
  roots: string[];
}

export interface BuildIndexResponse {
  fileCount: number;
  elapsedMs: number;
}

export interface SearchRequest {
  query: string;
  limit: number;
}

export interface SearchResponse {
  hits: Hit[];
  elapsedMicros: number;
}

export interface CoreInfoRequest {}

export interface CoreInfoResponse {
  version: string;
  indexedFiles: number;
}

/** Rust core 的类型化客户端。每个方法都是一次跨 WebView → 原生壳 → Rust 的往返。 */
export const ipc = {
  /** 扫描给定根目录，在 Rust 侧建立文件索引 */
  buildIndex(request: BuildIndexRequest): Promise<BuildIndexResponse> {
    return invoke<BuildIndexRequest, BuildIndexResponse>("buildIndex", request);
  },
  /** 在已建索引上做模糊搜索，按得分排序返回 */
  search(request: SearchRequest): Promise<SearchResponse> {
    return invoke<SearchRequest, SearchResponse>("search", request);
  },
  /** 读取 core 版本与当前索引规模 */
  coreInfo(request: CoreInfoRequest): Promise<CoreInfoResponse> {
    return invoke<CoreInfoRequest, CoreInfoResponse>("coreInfo", request);
  },
};
